In [3]:
import numpy as np

a1 = np.array([[1, 2, 3], [10, 20, 30]])
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
6


In [6]:
a2 = np.arange(20).reshape(4, 5) # 1차원 배열을 2차원 배열로 재정렬
print(a2)
print(a2.shape) #(20, )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [9]:
a3 = a2.flatten() # 깊은 복사
a3[3] = 100
print(a3)
print(a2)

a4 = a2.ravel() # 얕은 복사
a4[3] = 200
print(a4)
print(a2)

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[  0   1   2 200   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [18]:
a2 = np.arange(20).reshape(4, 5)
print(a2)
# print(a2[1])
# print(a2[1, 2])
# print(a2[:, 1])
# print(a2[:, 1:4]) # 원본에서 1~3까지 들고옴
# print(a2[:, 1:4:2])
# print(a2[1, :])
# print(a2[1:3, :])
# print(a2[::2, :])
print(a2[::2, 1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3]
 [11 12 13]]


In [ ]:
a10 = np.arange(5, 20).reshape(3, 5)
print(a10, a10.shape)

# shpe (3, 5)의 2차원 ndarray로 만들기
prihnt(a10[:], 2:4)
