In [5]:
import numpy as np
# 리스트와 같지만 좀 더 계산을 위한 형식

In [8]:
a1 = np.array([1, 2, 3, 4, 5]) # list를 ndarray로 변환
print([1, 2, 3, 4, 5])
print(a1)
print(type(a1))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
a2 = np.arange(10)
print(a2)

# 변수 a3, 100 아래 3의 배수
a3 = np.arange(3, 100, 3) # start, stop, step
print(a3)

# 1에서부터 10아래 0.5씩 증가하는 숫자
a4 = np.arange(1.3, 10, 0.5) 
print(a4)

# lista = [i for i in range(1.3, 10, 0.5)] # 소수점 안들어감

[0 1 2 3 4 5 6 7 8 9]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[1.3 1.8 2.3 2.8 3.3 3.8 4.3 4.8 5.3 5.8 6.3 6.8 7.3 7.8 8.3 8.8 9.3 9.8]


In [17]:
 # 공간을 구분함
 # stop이 포함되는 특징을 가진다.
a4 = np.linspace(0, 10, 3) 
print(a4)

[ 0.  5. 10.]


In [20]:
# 정수형이 아닌 실수형으로 들어가기 때문에 .이 들어감
# 0으로 채우기
a5 = np.zeros(5)
print(a5)

# 1로 채우기
a6 = np.ones(5)
print(a6)
a6.astype(np.float64)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


array([1., 1., 1., 1., 1.])

In [24]:
# 실수로 강제 형변환
lista = [1, 2, 3.5, 4.2]
a7 = np.array(lista)
print(a7)

# 문자열로 강제 형변환
listb = [1, 2, 'abc', "def"]
a8 = np.array(listb)
print(a8)
# a8.astype(np.int64)

[1.  2.  3.5 4.2]
['1' '2' 'abc' 'def']


In [27]:
#a8.dtype # ('<U11') = 유니코드라는 뜻
print(a7.dtype)
print(a7.ndim) #몇차원 array인지를 물어보는 것 
print(a7.shape) #어떤 모양인지를 물어보는 것 , 투플형태로 일차원 배열이라는 결과가 나옴 
print(a7.size) #이 배열안에 있는 모든 elument들의 갯수 

print(a7.itemsize) #데이터 타입의 byte사이즈
print(a7.data)

float64
1
(4,)
4
8


In [29]:
a10 = np.arange(10, 100, 5)
print(a10)

# 특정인덱스
print(a10[0], a10[-1])

# start, stop
print(a10[3:7])

# start, stop, step
print(a10[2:9:2])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
10 95
[25 30 35 40]
[20 30 40 50]


In [32]:
a10 = np.arange(10, 100, 5)
print(a10)
print(a10[[1, 3, 7]]) # 일정하지 않은 리스트에서 특정 인덱스값을 뽑아오는 것이 가능하나 파이썬의 list에서는 불가능

# 파이썬 리스트
list10 = [x for x in range(10, 100, 5)]
print(list10)
# print(list10[[1, 3, 7]])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 45]
[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [37]:
# 조건식으로 필터링 가능
a10 = np.arange(10, 100, 5)
print(a10)
print(a10[a10 % 10 == 5])

# 조건식 자체가 ndarray를 만듬
# bool list를 만들어서 필터링을 함
x = (a10 % 10 == 5)
print(x) 
print(x.shape)
print(a10.shape)
print(a10[x]) # a10[bool list의 조건식]

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 35 45 55 65 75 85 95]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True]
(18,)
(18,)
[15 25 35 45 55 65 75 85 95]


In [40]:
lista = [x for x in range(5)]
listb = [x for x in range(10, 15)]
print(lista)
print(listb)
print(lista + listb)
# print(lista - listb) # 오류남

[0, 1, 2, 3, 4]
[10, 11, 12, 13, 14]


[0, 1, 2, 3, 4, 10, 11, 12, 13, 14]

In [43]:
# ndarray list 합치기
a1 = np.arange(5)
a2 = np.arange(10, 15)
print(a1)
print(a2)
# 파이썬 list에서는 두 list를 연결시켜주지만
# ndarray는 같은 인덱스끼리 + 계산됨
# 사칙연산이 되려면 두 array의 길이가 같아야 함
print('add: ', a1 + a2)
print(np.concatenate((a1, a2))) # 붙이고 싶은 array를 튜플로 묶어줘야함
print('sub: ', a1 - a2)
print('mul: ', a1 * a2)
print('div: ', a1 / a2)

[0 1 2 3 4]
[10 11 12 13 14]
add:  [10 12 14 16 18]
[ 0  1  2  3  4 10 11 12 13 14]
sub:  [-10 -10 -10 -10 -10]
mul:  [ 0 11 24 39 56]
div:  [0.         0.09090909 0.16666667 0.23076923 0.28571429]
