In [4]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(100, 110)
print(a1, a2)
# print(a1 + a2)

a3 = np.array([5] * 10)
print(a3)
print(a1 + a3)
print(a1 + 5)

[0 1 2 3 4 5 6 7 8 9] [100 101 102 103 104 105 106 107 108 109]
[5 5 5 5 5 5 5 5 5 5]
[ 5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13 14]


In [6]:
# f(x) = 3x + 5
# x = 0에서 100사이 짝수

print(a2 + a3)

# a2 : (5, 6)
# 스칼라
# a3 : (6, )
# a4 : (5, 6)

[105 106 107 108 109 110 111 112 113 114]


In [8]:
a10 = np.arange(3 * 5 * 7 * 8).reshape(3, 5, 7, 8)
print(a10.shape)

# 스칼라
# (8, )
# (5, 7, 8)
# (3, 5, 7, 8)

(3, 5, 7, 8)


In [12]:
a15 = np.arange(15).reshape(5, 3)
print(a15)

# axis1 3개의 값 중
#  - 첫번째 곱하기 2
#  - 두번째 곱하기 10
#  - 세번째 곱하기 12
# axis1을 따라 합계 구하기
#       array([34, 106, 178, 250, 322])

x = np.array([2, 10, 12])
# print(x, x.shape)
x1 = a15 * x
# print(x1)
print(np.sum(x1, axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 34 106 178 250 322]
